### ISSUE TITLE
Script does not account for all the closed issues.

### ISSUE THREAD

**Issue by Predelnik** [diasurgical/devilution-progress#1]
Looks like number of closed issues is limited to 25 per page, that's why looking at only first page is not enough.

**Comment by mewmew** [comment]
> Looks like number of closed issues is limited to 25 per page, that's why looking at only first page is not enough.

Haha, we are fixing issues too fast for the tool to have a chance to keep up :)

Thanks for noticing this! It has now been fixed.

The updated states are as follows:

Before fix:
```
$ devilution-progress
progress: 93.33% (1624/1740)
```

After fix:
```
$ devilution-progress
progress: 93.82% (1762/1878)
```

**Comment by ghost** [comment]
116 left to go!
