### ISSUE TITLE
How to make the install instructions work?

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilution-progress#2]
`go get -u github.com/diasurgical/devilution-progress` does something. But afterward, the command is not available as advertised. What is required for having Go programs work with this way of installing in general (maybe add a reference to the readme)?

**Comment by mewmew** [comment]
To have the command available you need to add `$GOPATH/bin` to the `PATH` environment variable.

Add to `.bashrc` e.g.:

```bash
export GOPATH=${HOME}/go
export PATH=${HOME}/${GOPATH}/bin:$PATH
```

After this you should be able to run `devilution-progress`.

**Comment by mewmew** [comment]
@AJenbo, did it work for you after adding the `$GOPATH/bin` directory to your PATH?

If so, feel free to close this issue.

Also, note that `devilution-progress` is now updated to report the progress for the [Hellfire milestone](https://github.com/diasurgical/devilution/milestone/4).

**Edit:**

As of today, the progress is:

```
$ devilution-progress
progress: 55.65% (1103/1982)
```
